  version: 2
  updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
        interval: "daily"
      allow:
      - dependency-type: all
      groups:
        babel:
          patterns:
          - "@babel/*"
    - package-ecosystem: github-actions
      directory: /
      schedule:
        interval: "daily"
