name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          yarn install --frozen lockfile

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4.1.0
        with:
          command: "run"
          headless: true
          browsers: chrome
