name: Publish documentation to GH Pages

on:
  push:
    branches:
      - 'main'

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: "Cache dependencies"
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}build-node-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-build-node-

    - name: "Install documentation dependencies"
      run: yarn install --frozen-lockfile

    - name: "Build documentation"
      run: yarn build

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
        cname: zebra.efrane.com
